---
title: "Detailed Example"
author: "Eliora Henzler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Detailed Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, results='hide', message=FALSE,warning=FALSE,error=FALSE}
library("cleaninginspectoR")
library("dplyr")
library("questionr")
library("reshape2")
```

# Generating a fake data frame 
```{r}
data <- data.frame(a= c(runif(99),7287),
                   b=sample(letters,100,T),
                   uuid=c(1:98, 4,20),
                   water.source.other = c(rep(NA,98),"beer","neighbour' well"),
                   GPS.lat = runif(100)
                   )
```

## Finding duplicates in the data 

### Generic version with column name

```{r,eval=F}
find_duplicates(data, duplicate.column.name = "uuid")
```
```{r,echo=F}
knitr::kable(find_duplicates(data, duplicate.column.name = "uuid"))
```

### Gives you the same result as

```{r,eval=F}
find_duplicates_uuid(data)
```
```{r,echo=F}
knitr::kable(find_duplicates_uuid(data))
```

## Checking for outliers

```{r,eval=F}
find_outliers(data)

```
```{r,echo=F}
knitr::kable(find_outliers(data))

```


## Checking for other responses

```{r,eval=F}
find_other_responses(data)
```
```{r,echo=F}
knitr::kable(find_other_responses(data))

```

## Checking for sensitive data columns
```{r, eval=F}
sensitive_columns(data)
```
```{r, echo=F}
knitr::kable(sensitive_columns(data))
```
